#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  16000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

// 使用单工 I2S 模式（麦克风输入 + 功放输出，独立 I2S 外设）
#define AUDIO_I2S_METHOD_SIMPLEX

#ifdef AUDIO_I2S_METHOD_SIMPLEX
// 麦克风 I2S 引脚（ZTS6672，兼容 INMP441 时序）
#define AUDIO_I2S_MIC_GPIO_WS   GPIO_NUM_4   // LRC 左右时钟
#define AUDIO_I2S_MIC_GPIO_SCK  GPIO_NUM_6   // BCLK 位时钟
#define AUDIO_I2S_MIC_GPIO_DIN  GPIO_NUM_5   // DOUT 数据输出

// 功放 I2S 引脚（CH98357 / MAX98357A）
// BCLK/LRCK 与麦克风共享同一 I2S 总线
#define AUDIO_I2S_SPK_GPIO_DOUT GPIO_NUM_7   // DIN 数据输入
#define AUDIO_I2S_SPK_GPIO_BCLK GPIO_NUM_6   // 与麦克风共享 BCLK
#define AUDIO_I2S_SPK_GPIO_LRCK GPIO_NUM_4   // 与麦克风共享 LRCK
#else
// 双工模式（备用）
#define AUDIO_I2S_GPIO_WS   GPIO_NUM_4
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_6
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_5
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_7
#endif

// LED 和按键
#define BUILTIN_LED_GPIO        GPIO_NUM_48
#define BOOT_BUTTON_GPIO        GPIO_NUM_0
#define VOLUME_UP_BUTTON_GPIO   GPIO_NUM_38
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_39

// 显示 SPI 引脚（ST7789 240x320，使用 U7 主连接器）
#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_42
#define DISPLAY_MOSI_PIN      GPIO_NUM_47
#define DISPLAY_CLK_PIN       GPIO_NUM_21
#define DISPLAY_DC_PIN        GPIO_NUM_40
#define DISPLAY_RST_PIN       GPIO_NUM_45
#define DISPLAY_CS_PIN        GPIO_NUM_41

#if defined(CONFIG_LCD_ST7789_240X320) || defined(CONFIG_LCD_ST7789_240X320_NO_IPS)
#define LCD_TYPE_ST7789_SERIAL
#define DISPLAY_WIDTH   240
#define DISPLAY_HEIGHT  320
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false
#define DISPLAY_OFFSET_X  0
#define DISPLAY_OFFSET_Y  0
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false
#define DISPLAY_SPI_MODE 0

#ifdef CONFIG_LCD_ST7789_240X320
#define DISPLAY_INVERT_COLOR    true
#else
#define DISPLAY_INVERT_COLOR    false
#endif

#define DISPLAY_RGB_ORDER  LCD_RGB_ELEMENT_ORDER_RGB
#endif

// MPU-6500 I2C 引脚（地址 0x68，AD0 = GND）
#define IMU_I2C_SDA_PIN GPIO_NUM_11
#define IMU_I2C_SCL_PIN GPIO_NUM_12

// 电池电量检测 ADC 引脚（IO2 = ADC1_CH1，100k+100k 分压，比例 0.5）
#define BATTERY_ADC_CHANNEL    ADC_CHANNEL_1
#define BATTERY_UPPER_RESISTOR 100000.0f
#define BATTERY_LOWER_RESISTOR 100000.0f

// ========== 机械臂 UART1 配置 ==========
// UART1 连接 LeRobot SO101 驱动板
// TX=IO9 -> 驱动板 RX, RX=IO10 <- 驱动板 TX
#define ROBOT_ARM_UART_PORT       UART_NUM_1
#define ROBOT_ARM_UART_TXD_PIN    GPIO_NUM_9
#define ROBOT_ARM_UART_RXD_PIN    GPIO_NUM_10
#define ROBOT_ARM_UART_BAUD_RATE  115200
#define ROBOT_ARM_UART_BUF_SIZE   256

#endif // _BOARD_CONFIG_H_