#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  16000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

// 如果使用 Duplex I2S 模式，请注释下面一行
#define AUDIO_I2S_METHOD_SIMPLEX

#ifdef AUDIO_I2S_METHOD_SIMPLEX

#define AUDIO_I2S_MIC_GPIO_WS   GPIO_NUM_4
#define AUDIO_I2S_MIC_GPIO_SCK  GPIO_NUM_5
#define AUDIO_I2S_MIC_GPIO_DIN  GPIO_NUM_6
#define AUDIO_I2S_SPK_GPIO_DOUT GPIO_NUM_7
#define AUDIO_I2S_SPK_GPIO_BCLK GPIO_NUM_15
#define AUDIO_I2S_SPK_GPIO_LRCK GPIO_NUM_16

#else

#define AUDIO_I2S_GPIO_WS GPIO_NUM_4
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_5
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_6
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_7

#endif


#define BUILTIN_LED_GPIO        GPIO_NUM_48
#define BOOT_BUTTON_GPIO        GPIO_NUM_0
#define TOUCH_BUTTON_GPIO       GPIO_NUM_47
#define VOLUME_UP_BUTTON_GPIO   GPIO_NUM_40
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_39

#define DISPLAY_SDA_PIN GPIO_NUM_41
#define DISPLAY_SCL_PIN GPIO_NUM_42
#define DISPLAY_WIDTH   128

#if CONFIG_OLED_SSD1306_128X32
#define DISPLAY_HEIGHT  32
#elif CONFIG_OLED_SSD1306_128X64
#define DISPLAY_HEIGHT  64
#elif CONFIG_OLED_SH1106_128X64
#define DISPLAY_HEIGHT  64
#define SH1106
#else
#error "OLED display type is not selected"
#endif

#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y true

// ========== 机器狗 4 路舵机引脚（LEDC PWM, 50Hz） ==========
// M1=右前, M2=右后, M3=左前, M4=左后
#define SERVO_RIGHT_FRONT_PIN  GPIO_NUM_13   // M2 右前舵机
#define SERVO_RIGHT_BACK_PIN   GPIO_NUM_14   // M4 右后舵机
#define SERVO_LEFT_FRONT_PIN   GPIO_NUM_17   // M1 左前舵机
#define SERVO_LEFT_BACK_PIN    GPIO_NUM_18   // M3 左后舵机

// ========== 开关式触摸传感器（GPIO 输入，内部上拉） ==========
#define TOUCH_SENSOR_LEFT_PIN   GPIO_NUM_8   // IO8, 左触须
#define TOUCH_SENSOR_FRONT_PIN  GPIO_NUM_19  // IO19, 前触须
#define TOUCH_SENSOR_RIGHT_PIN  GPIO_NUM_20  // IO20, 右触须

#endif // _BOARD_CONFIG_H_
